# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: albertshih
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ucmerced-status-xm
# serverless.yml
service: ucmerced-status-xmodule
provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment:
    uiExamplesToken: Basic bW9kb3NlcnZpY2U6Z2hwX3lFeE84MEZHNzZUUndtRm1KY1RBOXZjUHRXRkVoRTAzdHJrNg==
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
